export const enum RoutePath {
  DesignSystem = '/design-system',
  Icons = 'icons',
  Buttons = 'buttons',
  Checkboxes = 'checkboxes',
  Inputs = 'inputs',
  Forms = 'forms',
  Layout = 'layout',
  Links = 'links',
  CalendarDropdown = 'calendar-dropdown',
  CalendarRangeDropdown = 'calendar-range-dropdown',
  SimpleSelect = 'simple-select',
  MultipleSelect = 'multiple-select',
  Tags = 'tags',
  Hint = 'hint',
  Tree = 'tree',
  DropDown = 'drop-down',
  Table = 'table',
  PortalTable = 'portal-table',
  Accordion = 'accordion',
  SnackBar = 'snack-bar',
}
